#!/bin/bash

RETVAL=1
while IFS="" read -r p || [ -n "$p" ]
do
  if [[ $p =~ (^CFDEX-[0-9]+) ]]; then
    RETVAL=0
  fi
done < $1

if [[ "$RETVAL" -eq "1" ]]; then
  >&2 echo "ERROR: Invalid commit message; the commit message must contain a line referencing the project."
  >&2 echo "Example commit message: CFDEX-123 My awesome commit"
fi

exit $RETVAL
